using SoulsFormats;

namespace EldenRingSurvivalMode
{
    internal static class Params
    {
        class CSVRow
        {
            public int ID { get; }
            public string Name { get; }
            public List<string> Values { get; }

            public CSVRow(string csvRow, char separator = ';')
            {
                csvRow = csvRow.TrimEnd(separator);
                string[] values = csvRow.Split(separator);
                ID = int.Parse(values[0]);
                Name = values[1];
                Values = new List<string>();
                for (int i = 2; i < values.Length; i++)
                    Values.Add(values[i]);
            }

            public void ApplyToRow(PARAM.Row row)
            {
                row.ID = ID;
                row.Name = Name;

                List<PARAM.Cell> nonPadCells = row.Cells.Where(cell => cell.Def.DisplayType != PARAMDEF.DefType.dummy8).ToList();
                if (nonPadCells.Count != Values.Count)
                {
                    Console.WriteLine("Non-padding cells:");
                    foreach (var cell in nonPadCells)
                    {
                        Console.WriteLine($"    {cell.Def.InternalName} | {cell.Def.InternalType}");
                    }
                    //foreach (var value in Values)
                    //{
                    //    Console.WriteLine($"    Value: {value}");
                    //}
                    throw new Exception($"Number of CSV cells ({Values.Count}) does not match number of non-padding PARAM cells ({nonPadCells.Count})");
                }
                    
                for (int i = 0; i < Values.Count; i++)
                    nonPadCells[i].Value = Values[i];  // `SoulsFormats` will convert string to appropriate type automatically
            }

            public static void ApplyAllRows(IEnumerable<CSVRow> rows, PARAM param)
            {
                int csvRowCount = rows.Count();
                int currentParamRowsCount = param.Rows.Count;
                if (currentParamRowsCount < csvRowCount)
                {
                    // Add default PARAM rows to catch up.
                    for (int i = 0; i < csvRowCount - currentParamRowsCount; i++)
                    {
                        PARAM.Row newRow = new(-1, "", param.AppliedParamdef);
                        param.Rows.Add(newRow);
                    }
                }
                else if (csvRowCount < param.Rows.Count)
                {
                    // Delete PARAM rows.
                    param.Rows = param.Rows.GetRange(0, csvRowCount);
                }

                int rowIndex = 0;
                foreach (CSVRow row in rows)
                {
                    PARAM.Row paramRow = param.Rows[rowIndex++];
                    row.ApplyToRow(paramRow);
                }
            }
        }

        const string CSV_PATH = @"C:\Dark Souls\Projects\EldenRingSurvivalMode\EldenRingSurvivalMode\CSV";
        const string DIST_PATH = @"C:\Dark Souls\Projects\EldenRingSurvivalMode\dist\Game (OPTIONS)";

        static Dictionary<string, string> Modes { get; } = new Dictionary<string, string>
        {
            ["Survival"] = @"Survival ENABLED\Weapon Tree DISABLED\Diseases DISABLED",
            ["Weapons"] = @"Survival DISABLED\Weapon Tree ENABLED\Diseases DISABLED",
            ["Diseases"] = @"Survival DISABLED\Weapon Tree DISABLED\Diseases ENABLED",
            ["Survival_Weapons"] = @"Survival ENABLED\Weapon Tree ENABLED\Diseases DISABLED",
            ["Survival_Diseases"] = @"Survival ENABLED\Weapon Tree DISABLED\Diseases ENABLED",
            ["Weapons_Diseases"] = @"Survival DISABLED\Weapon Tree ENABLED\Diseases ENABLED",
            ["Survival_Weapons_Diseases"] = @"Survival ENABLED\Weapon Tree ENABLED\Diseases ENABLED",
        };

        /// <summary>
        /// Convert Yapped CSV files (generated by my Python code) into
        /// `regulation.bin` files for play.
        /// 
        /// This function only serves to remove Yapped from the equation
        /// for now, rather than functioning as an actual new installer
        /// (since Python is still required). 
        /// </summary>
        public static void CSVToRegulation(string csvDirectory, string regulationPath)
        {
            if (!File.Exists("regulation.bin"))
                throw new Exception($"Could not find (vanilla) `regulation.bin` next to executable.");

            BND4 parambnd = SFUtil.DecryptERRegulation("regulation.bin");

            List<PARAMDEF> paramdefs = LoadParamdefs("Defs");

            foreach (string csvFile in Directory.GetFiles(csvDirectory))
            {
                string fileName = Path.GetFileName(csvFile);
                if (!fileName.EndsWith(".csv"))
                    continue;
                string paramName = Path.GetFileNameWithoutExtension(fileName);
                BinderFile parambndFile = parambnd.Files.Where(x => x.Name == $@"N:\GR\data\Param\param\GameParam\{paramName}.param").First();
                PARAM param = PARAM.Read(parambndFile.Bytes);
                param.ApplyParamdefCarefully(paramdefs);
                List<CSVRow> paramCSV = LoadParamCSV(csvFile);
                CSVRow.ApplyAllRows(paramCSV, param);
                parambndFile.Bytes = param.Write();
            }

            SFUtil.EncryptERRegulation(regulationPath, parambnd);
        }

        public static void AllVariantsCSVToRegulation()
        {
            foreach (KeyValuePair<string, string> kvp in Modes)
            {
                string csvSubdir = kvp.Key;
                string distSubdir = kvp.Value;
                CSVToRegulation(Path.Combine(CSV_PATH, csvSubdir), Path.Combine(DIST_PATH, distSubdir, "regulation.bin"));
                Console.WriteLine($"Saved `regulation.bin` for variant: {csvSubdir}");
            }
        }

        /// <summary>
        /// Load ParamDefs from Paramdex XMLs.
        /// </summary>
        /// <returns></returns>
        static List<PARAMDEF> LoadParamdefs(string defsDirectory)
        {
            List<PARAMDEF> defs = new();
            foreach (string file in Directory.GetFiles(defsDirectory))
            {
                PARAMDEF paramdef = PARAMDEF.XmlDeserialize(file);
                defs.Add(paramdef);
            }
            return defs;
        }

        /// <summary>
        /// Read a Yapped CSV into a list of PARAM rows (which are each a list of string values).
        /// 
        /// Each row starts with its ID, then Name, then its non-padding values.
        /// </summary>
        /// <param name="csvPath"></param>
        /// <returns></returns>
        static List<CSVRow> LoadParamCSV(string csvPath)
        {
            List<CSVRow> rows = new();
            bool headerRead = false;
            foreach (string line in File.ReadLines(csvPath))
            {
                if (!headerRead)
                {
                    string[] header = line.Split(';');
                    headerRead = true;
                    continue;
                }
                rows.Add(new CSVRow(line));
            }
            return rows;
        }
    }
}
